name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install
        run: pnpm install --no-frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test
